[Travis] Synchronize.

diff --git a/.travis/after_success b/.travis/after_success
--- a/.travis/after_success
+++ b/.travis/after_success
@@ -23,7 +23,7 @@ if [ -d debian ]; then
 	    dput ppa:${PPA_URI} "$build_dir"/export/*_source.changes
 	fi
     fi
-else
+elif [[ ${TRAVIS_OS_NAME} = linux ]]; then
     if [ ! x${DIST} = x ]; then
 	echo "skipping this build"
 	exit 0
@@ -34,9 +34,21 @@ else
 
     # Upload coveralls data.
     if [ x${CC} = xgcc ]; then
+	cd $build_dir
 	# If tests failed, coveralls data may not have been written
-	coveralls -b "$build_dir" -e $install_dir &> coveralls.log || true
-	cat coveralls.log || true
+	lcov --directory $build_dir --base-directory $root_dir --capture --output-file coverage.info || true
+	lcov --remove coverage.info '/usr*' "$install_dir*" -o coverage.info || true
+	if `! test x${LCOV_IGNORE_RULES} = x`; then
+            # Note: ignore rules are given by a string such as "*test* *foo*"
+            # lcov expects: '*test*' '*foo*'
+            # We use -f to prevent expansion of *
+            set -f
+	    lcov --remove coverage.info ${LCOV_IGNORE_RULES} -o coverage.info || true
+            set +f
+	fi
+	cd $root_dir
+	coveralls-lcov "$build_dir/coverage.info" || true
+	cd -
     else
 	echo "skipping coveralls upload in non-gcc builds"
     fi
@@ -57,12 +69,12 @@ else
 	COVERITY_TARBALL=coverity-${PROJECT_NAME}-${PROJECT_VERSTION}.tgz
 	tar czvf ${COVERITY_TARBALL} cov-int
 	curl -s --form project=${PROJECT_NAME}			\
-	     --form token=${COVERITY_TOKEN}			\
-	     --form email=thomas.moulard@gmail.com		\
-	     --form file=@$build_dir/${COVERITY_TARBALL}	\
-	     --form version=${PROJECT_VERSION}			\
-	     --form description="${PROJECT_NAME} v${PROJECT_VERSION} (Travis upload)" \
-	     http://scan5.coverity.com/cgi-bin/upload.py
+	    --form token=${COVERITY_TOKEN}			\
+	    --form email=thomas.moulard@gmail.com		\
+	    --form file=@$build_dir/${COVERITY_TARBALL}	\
+	    --form version=${PROJECT_VERSION}			\
+	    --form description="${PROJECT_NAME} v${PROJECT_VERSION} (Travis upload)" \
+	    http://scan5.coverity.com/cgi-bin/upload.py || true
 	cd $root_dir
     else
 	echo "coverity support is disabled in this build"
@@ -70,34 +82,39 @@ else
 
     # If it's not a fork or a pull request
     if `test x${TRAVIS_REPO_SLUG} = x${GH_REPO} -a ${TRAVIS_PULL_REQUEST} = false`; then
-	# Set the push capable URL.
-	#
-	# Add the possibility to use three variables instead of one to
-	# work around string maximum length limitation issue.
-	if `test x${GH_PUSH_URI} = x`; then
-	    export GH_PUSH_URI=https://${GH_USERNAME}:${GH_TOKEN}@github.com/${GH_REPO}
+	# If encrypted username/tokens were not provided
+	if `test x${GH_TOKEN} = x -o x${GH_USERNAME} = x`; then
+	    echo "missing username and/or token for GitHub push"
+	else
+	    # Set the push capable URL.
+	    #
+	    # Add the possibility to use three variables instead of one to
+	    # work around string maximum length limitation issue.
+	    if `test x${GH_PUSH_URI} = x`; then
+		export GH_PUSH_URI=https://${GH_USERNAME}:${GH_TOKEN}@github.com/${GH_REPO}
+	    fi
+	    git remote set-url origin "${GH_PUSH_URI}"
+
+	    # Update the documentation.
+	    # Retrieve last commit of the gh-pages branch.
+	    git fetch --depth=1 origin gh-pages:gh-pages
+
+	    cd $build_dir/doc && $root_dir/cmake/github/update-doxygen-doc.sh \
+		-r $root_dir -b $build_dir
+
+	    # Push git note indicating success
+	    cd $root_dir
+	    notes_msg="Successful build.\n----\n\nDependencies commit id:"
+	    for package in ${GIT_DEPENDENCIES}; do
+		cd $build_dir/$package
+		commitid=`git rev-parse HEAD || echo unknown`
+		notes_msg="${notes_msg} $package : $commitid\n"
+	    done
+	    cd $root_dir
+	    git fetch --quiet --force origin refs/notes/travis:refs/notes/travis || true
+	    git notes --ref=travis add -f -m "$(echo "${notes_msg}")" $HEAD
+	    git push origin refs/notes/travis --force
 	fi
-	git remote set-url origin "${GH_PUSH_URI}"
-
-	# Update the documentation.
-	# Retrieve last commit of the gh-pages branch.
-	git fetch --depth=1 origin gh-pages:gh-pages
-
-	cd $build_dir/doc && $root_dir/cmake/github/update-doxygen-doc.sh \
-	    -r $root_dir -b $build_dir
-
-	# Push git note indicating success
-	cd $root_dir
-	notes_msg="Successful build.\n----\n\nDependencies commit id:"
-	for package in ${GIT_DEPENDENCIES}; do
-	    cd $build_dir/$package
-	    commitid=`git rev-parse HEAD || echo unknown`
-	    notes_msg="${notes_msg} $package : $commitid\n"
-	done
-	cd $root_dir
-	git fetch --quiet --force origin refs/notes/travis:refs/notes/travis || true
-	git notes --ref=travis add -f -m "$(echo "${notes_msg}")" $HEAD
-	git push origin refs/notes/travis --force
     else
 	echo "skipping doc/build result upload on forks and for pull requests"
     fi
